Pier1/rocketbelt

- rocketbelt/components/tags/_tags-dismissable.jade
- rocketbelt/components/tags/_tags-sizes.jade
- rocketbelt/components/tags/_tags-stretch.jade
- rocketbelt/components/tags/_tags.scss
- templates/js/playground.jquery.js
Made default tag size smaller, reduced number of size variants to three.
> Adjusting tag sizes

- rocketbelt/creative/_creative.scss
- rocketbelt/creative/seo-banner/_seo-banner.jade
- rocketbelt/creative/seo-banner/_seo-banner.scss
- rocketbelt/rockebelt.creative.scss
- rocketbelt/rocketbelt.creative.scss
- rocketbelt/rocketbelt.scss
- templates/_layout.jade
- templates/creative/seo-banner/index.jade
Mobile-first SEO Banner. Template made customizable w/ Playground. 
PR also includes:
-- separated creative.css from site.css
-- added creative.css to layout.jade file to be included site-wide
> Seo Banner

- rocketbelt/creative/_creative.scss
- rocketbelt/creative/product-tag/_product-tag.jade
- rocketbelt/creative/product-tag/_product-tag.scss
- templates/creative/product-tag/index.jade
- templates/scss/_creative.scss
Product-specific messaging tag. Typically used for sale promotions from product category pages. Playground interactions included ability to customize copy/sale-amount and generate preview (and HTML) with or without the backing image.
> Product tags

- rocketbelt/creative/sale-sticker/_sale-sticker.scss
- templates/creative/sale-sticker/index.jade
Added a full-width variant where the sticker will extend to the width of it's container.
Also in this PR:
Made text in the 'Up To' slot uppercase on all variations based on Creatives' feedback from 11/09
> added full-width variation, uppercase up-to on all versions

- templates/_mixins.pug
Updates color picker mixin to use pug style string concatenation
> Pug fix color picker

- rocketbelt/components/navigation/rocketbelt.navigation-xl.js
Needed this because the mega menu was super annoying on pier1.com
> Add 250ms timeout to _mouseOverHandler on mega menu

- rocketbelt/components/navigation/rocketbelt.navigation-xl.js
These changes were never merged in because of the IE9 support code.
> Fix closing of nav menu with link and escape

- rocketbelt/components/tooltips/_tooltips.scss
- templates/components/tooltips/index.pug
Updates to CSS:
Small aesthetic adjustments
Allow pointer events
Remove unnecessary css content property
Adding accessibility to all example tooltips
> tooltipReduxv2

- rocketbelt/components/tabcordions/rocketbelt.tabcordions.js
Use correct RB namespace. Nam's PR can be remove.
> Fire event on tabcordion click. 

- rocketbelt/creative/sale-sticker/_sale-sticker.scss
- templates/creative/sale-sticker/index.pug
Updating with Creative Approved sale sticker variant.
> init sale-sticker x for $ promo variant

- rocketbelt/components/forms/_forms-basic.pug
- rocketbelt/components/forms/_forms-inline.pug
- rocketbelt/components/forms/_forms-invalid.pug
- rocketbelt/components/forms/_forms.scss
Implement textareas within forms as well as fix invalidness of inputs.
> feat(Forms): Implement textareas within forms.

- rocketbelt/rocketbelt.legacy.grid.scss
> init rocketbelt.legacy.grid.scss

- rocketbelt/components/icons/rocketbelt.icons.svgxuse.js
SVG's were not working in IE9 due to cors
> Remove CORS request from SVG shim

- rocketbelt/components/images/rocketbelt.images-gallery.js
Needed to keep image gallery from changing images when zoom panning
> Add allowTouchSwipePrev and allowTouchSwipeNext

- rocketbelt/creative/sale-sticker/_sale-sticker.scss
Re-ordered properties to match spec. Removed important from optional-msg when empty. Disabled force-element-nesting until more time can be spent to refactor.
> Cleanup sales sticker sass.

- .sass-lint.yml
Added force-element-nesting to sass-lint.yml and updated nesting depth.
> Added force-element-nesting to sass-lint.yml and updated nesting depth.

- rocketbelt/components/tags/_tags-variations.pug
- rocketbelt/components/tags/_tags.scss
Shifted sale tag to sale color and appended error tag.
> feat(Tags): Add error variation to tags.

- rocketbelt/components/tags/_tags-variations.pug
- rocketbelt/components/tags/_tags.scss
- rocketbelt/tools/mixins/_color-contrast.scss
- rocketbelt/tools/mixins/_mixins.scss
Also added a contrasting color function for colors. Takes color and outputs either rb white, or rb black based on lightness on color provided.
> fix(Tags): Implement default font-weight for tags. Add more colors to tags.

- .eslintrc
- .gitignore
- rocketbelt/components/dialogs/_dialog-max.pug
- rocketbelt/components/dialogs/_dialog-max.scss
- rocketbelt/components/dialogs/_dialog-sheet.pug
- rocketbelt/components/dialogs/_dialog-standard.pug
- rocketbelt/components/dialogs/_dialog-template.pug
- rocketbelt/components/dialogs/rocketbelt.dialogs.js
- templates/_layout.pug
- templates/components/dialogs/index.pug
- templates/scss/site.scss
Added brace-style eslint rule. Vertically aligned 'copy' button for code snippets.
> refactor(Dialogs): Implement jQuery version of rocketbelt modals.

- rocketbelt/creative/_creative.scss
- rocketbelt/creative/product-grid/_product-grid.js
- rocketbelt/creative/product-grid/_product-grid.pug
- rocketbelt/creative/product-grid/_product-grid.scss
- templates/creative/product-grid/index.pug
TODO:
Decouple from dependencies and generalize
Add interaction (ability to add more tiles, ability to update tile values)
> Basic grid injector

- rocketbelt/tools/mixins/_z-depth.scss
> fix(Z-Depth): Change -1px top box-shadow to 0 for some stylistic purposes.

- rocketbelt/components/images/rocketbelt.images-gallery.js
Set focus on prev/next buttons on click.
> Added keyboard event bindings to container and prev/next buttons.

- rocketbelt/components/forms/_forms.scss
- rocketbelt/components/radio-buttons/_radio-buttons-default.scss
> namespacing checkboxes

- rocketbelt/components/forms/_forms.scss
> exclude input rules from checkboxes

- rocketbelt/base/typography/_typography-cta.scss
- rocketbelt/components/dialogs/_dialog-base.scss
- rocketbelt/components/dialogs/rocketbelt.dialogs.js
- templates/components/dialogs/index.pug
Combined changes from other PR and dialog fixes.
> Dialogs and cta fix

- rocketbelt/components/busy-indicators/rocketbelt.progress-indicators.js
- rocketbelt/components/dialogs/rocketbelt.dialogs.js
Verify classList exists before .contains
matches .js file jQuery reference to other files
> Minor Fixes

- rocketbelt/components/buttons/rocketbelt.buttons-dropdown.js
Previous method was throwing an error on each click for IE11 and below
> update way we check the event target

- rocketbelt/components/forms/_forms.scss
Fix flex basis and min width of stacked input with button
> Resolve #180

- rocketbelt/components/navigation/rocketbelt.navigation-xl.js
- rocketbelt/components/tooltips/rocketbelt.tooltips.js
Tooltip never to go off screen
add scrollbar to nav
> tooltips and navscroll

- package-lock.json
- package.json
- rocketbelt/components/busy-indicators/rocketbelt.progress-indicators.js
Had to update packages b/c of build error when running gulp processes
https://github.com/gulpjs/gulp/issues/2162
Added null-checks
> Progress indicators - Issue #197

- rocketbelt/base/rocketbelt.js
> Fix typo in NodeList.forEach polyfill

- rocketbelt/components/tabcordions/rocketbelt.tabcordions.js
> Unwrap jquery object when dispatching event

- rocketbelt/components/uploaders/rocketbelt.uploaders.js
- Upload photo button on mobile returns back to button when all photos cleared
- Able to re-add last removed image
> Fix uploader button on mobile

- src/components/navigation.js
This PR preps the navigation for styling & interactivity.
> feat(Sample Site): Dynamically generate <nav> elements.
